In [86]:
import pandas as pd

df = pd.read_csv('Camp_Election.Oracle/Correlates of State Policy/correlates2-6.csv')

/var/folders/2n/wzk06qbn21vdft6lfw86j15c0000gn/T/ipykernel_55947/1550990781.py:3: DtypeWarning: Columns (487,491,497,499,502,504,508,511,518,523,525,530,1496,1871,2106,2269,2270,2271,2272,2273,2274,2275,2276) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Camp_Election.Oracle/Correlates of State Policy/correlates2-6.csv')

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6171 entries, 0 to 6170
Columns: 3020 entries, st to introcat3pot
dtypes: float64(2971), int64(3), object(46)
memory usage: 142.2+ MB

In [90]:
null_percentage = df.isnull().mean() * 100
columns_to_drop = null_percentage[null_percentage > 70].index

df.drop(columns=columns_to_drop, inplace=True)

In [95]:
df.to_csv('modified_correlates.csv', index=False)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6171 entries, 0 to 6170
Columns: 893 entries, st to ppexpend
dtypes: float64(878), int64(3), object(12)
memory usage: 42.0+ MB

In [99]:
df

,st,stateno,state,state_fips,state_icpsr,year,evangelical_pop,nonwhite,pop_annual,immigration_english_language,...,dsl,electedpros,termlength,recall,sentencecomm,mand_min,YearCBrequired,CBrequired_SY,CBeverrequired,ppexpend
0,AK,2.0,Alaska,2,81,1900,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1970.0,0.0,1.0,NaN
1,AK,2.0,Alaska,2,81,1901,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AK,2.0,Alaska,2,81,1902,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AK,2.0,Alaska,2,81,1903,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AK,2.0,Alaska,2,81,1904,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1970.0,0.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6166,WY,50.0,Wyoming,56,68,2016,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6167,WY,50.0,Wyoming,56,68,2017,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6168,WY,50.0,Wyoming,56,68,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6169,WY,50.0,Wyoming,56,68,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6170,WY,50.0,Wyoming,56,68,2020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN